Update create-emr-cft-updated.yml

diff --git a/.github/workflows/create-emr-cft-updated.yml b/.github/workflows/create-emr-cft-updated.yml
--- a/.github/workflows/create-emr-cft-updated.yml
+++ b/.github/workflows/create-emr-cft-updated.yml
@@ -7,13 +7,13 @@ on:
 jobs:
   deployment:
     runs-on: ubuntu-latest
-    outputs:
-      id: ${{ steps.deploy-emr.id }}
-      value: ${{ steps.deploy-emr.outputs.deployment_error }}
-
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Checkout files
+        run: |
+          ls -l
 
       - name: Configure AWS credentials
         id: creds
@@ -37,8 +37,8 @@ jobs:
           stack-name: ${{ github.event.client_payload.inputs.stack-name }}
         run: |
           echo $stack-name &&
-          python luminex/validation/stack_name_validator.py 2>&1 | tee validation_error.log
-          echo "::set-output name=validation_error::$(cat validation_error.log)"
+          python luminex/validation/stack_name_validator.py ||
+          { echo "Validation failed. Check the logs for details."; exit 1; }
 
       - name: Deploy EMR cluster
         id: deploy-emr
@@ -49,5 +49,6 @@ jobs:
             --parameters file://./infrastructure/config_parameter.json \
             --role-arn \
             --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
-            | jq -r '.StackId') 2>&1 | tee deployment_error.log
-          echo "::set-output name=deployment_error::$(cat deployment_error.log)"
+            | jq -r '.StackId') &&
+          echo "CloudFormation stack ID: $stack_id" ||
+          { echo "Deployment failed. Check the logs for details."; exit 1; }
